---

# Travis configuration

dist: 'trusty'
sudo: 'required'

services:
  - 'docker'

language: 'python'

env:
  matrix:
    - TOXENV='py27-ansible22'
    - TOXENV='py27-ansible23'
    - TOXENV='py27-ansible24'

install:
  - 'pip install tox-travis'
  - 'sudo add-apt-repository -y ppa:ubuntu-lxc/lxd-stable'
  - 'sudo apt-get -qq update'
  - 'sudo apt-get -y install lxd'
  - 'sudo lxd init --auto'
  - 'sudo usermod -a -G lxd travis'
  - 'sudo su travis -c "lxc network create lxdbr0"'
  - 'sudo su travis -c "lxc network attach-profile lxdbr0 default eth0"'

script:
  - 'tox -e "${TOXENV}"'

notifications:
  webhooks: 'https://galaxy.ansible.com/api/v1/notifications/'
