---

dependency:
  name: 'galaxy'
  options:
    role-file: 'molecule/default/requirements.yml'
driver:
  name: 'lxd'
lint:
  name: 'yamllint'
platforms:
  - name: "pgadmin4-lxd-jessie"
    source:
      type: 'image'
      mode: 'pull'
      properties:
        os: 'debian'
        release: 'jessie'
        architecture: 'x86_64'
  - name: "pgadmin4-lxd-xenial"
    source:
      type: 'image'
      mode: 'pull'
      properties:
        os: 'ubuntu'
        release: '14.04'
        architecture: 'x86_64'
provisioner:
  name: 'ansible'
  lint:
    name: 'ansible-lint'
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: '/usr/bin/env python2.7'
    host_vars: {}
scenario:
  name: 'default'
verifier:
  name: 'testinfra'
  additional_files_or_dirs:
    - '../../tests'
  lint:
    name: 'flake8'
  options:
    sudo: True
